### ISSUE TITLE
Vault secret engine versions

### ISSUE THREAD

**Issue by ADRFranklin** [picostack/pico#18]
By default Vault uses the engine version 2 for key/value pairs. Wadsworth seems to expect version 1, and doesn't correctly handle version 2. 

This will cause credentials to not be correctly handled/passed to containers. 

Since version 2 is the default for engines being created at this current time, I think it makes sense to have an option for vault where you can specify which version you are using and then handle that internally. 

Though this may not need to exist, if there is a way in the vault api to detect which versions exist and to use that. Since it's not possible to have 2 versions of the same path, it makes more sense to detect it internally and to not require any more input from the end user.

**Comment by Southclaws** [comment]
This was actually really awkward - there's no API to check a secret engine version, so instead it must attempt to read/list various routes and make a guess at the version. It works except for a very specific case that doesn't matter.

Fixed in v1.3.5
